### ISSUE TITLE
Move deployment to services-targer namespace

### ISSUE THREAD

**Issue by johanneskiesel** [webis-de/targer#11]
We are moving all our demos to `services-demos`. I see targer is deployed in a `targer` namespace. Is this necessary? Where is the documentation for this namespace? Who has access to it? Why is it not listed in `webis k8s get-namespace-permission`?

I added @heinrichreimer to the people who can deploy to `services-demo` [here](https://git.webis.de/groups/auth/auth-services/demos/-/group_members). Please tell me if I should add more people, or just have the staff in your group do it. Note that you may have to [reset your token](https://git.webis.de/code-generic/code-webis-faq/-/blob/master/README.md#how-to-do-a-demoservice-permission-setup) for group membership to apply. If there is no reason not to, I would advise going the (now) standard way.

Also, using NodePorts is deprecated. The service should be switched to [ingress](https://git.webis.de/code-generic/code-admin-knowledge-base/blob/master/services/web-service-proxy/README.md#proxying-kubernetes-http-services). Several examples for how to do this can be found [here](https://git.webis.de/code-generic/code-admin-knowledge-base/-/tree/master/services/demo).

  - [x] namespace
  - [x] ingress

Once you have done this, ping me so that I can add a pointer to this repo [in the usual location](https://git.webis.de/code-generic/code-admin-knowledge-base/-/tree/master/services/demo).

**Comment by johanneskiesel** [comment]
Yes, that works, too. We mainly want to have an overview of who is allowed to do what, so that integration with Gitlab comes very handy.

I'll set up the gitlab group and kubernetes namespace for you.

**Comment by johanneskiesel** [comment]
Sounds good. Tell me when you have the ingress running so that I can switch our NGinx to use it instead of the NodePort.

Within VPN, you should be able to do reach it with this line even before I switch:
```
curl -H"Host: demo.webis.de"  http://betaweb001.medien.uni-weimar.de:30080/targer
```

**Comment by heinrichreimer** [comment]
Fixed in https://git.webis.de/code-generic/code-saltstack/-/merge_requests/13
